# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # - name: Hook_qwerty
    #  uses: distributhor/workflow-webhook@v1
    #  env:
    #    webhook_url: 'http://81.47.87.161:8080/github-webhook/'
    #    webhook_secret: 'P4ssw0rd'
    #    data: ''
    #- name: Webhook
    #  uses: joelwmale/webhook-action@master
    #  env:
    #    WEBHOOK_URL: 'http://81.47.87.161:8080/github-webhook/'
    #    data: "'{Hello from github actions!}'"
      - name: Webhook POST Action
        uses: muinmomin/webhook-action@v1.0.0
        with:
          # URL of webhook to send post request to
          url: 'http://81.47.87.161:8080/github-webhook/'
